# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Colores', models.CharField(max_length=200)),
                ('Dia_registro', models.DateTimeField(verbose_name='Fecha')),
            ],
        ),
    ]
